version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: task-manager
    ports:
      - '5431:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always